clc;
load('SVM.mat');
disp('Linear');
disp(mean(CTY==LS.predictFcn(CTX)));
disp('Quadratic')
disp(mean(CTY==QS.predictFcn(CTX)));
disp('Cubic');
disp(mean(CTY==CS.predictFcn(CTX)));
disp('Fine');
disp(mean(CTY==FS.predictFcn(CTX)));
disp('Medium');
disp(mean(CTY==MS.predictFcn(CTX)));
disp('Coarse');
disp(mean(CTY==CoS.predictFcn(CTX)));
disp('After changes');
disp('Linear');
disp(mean(CTY==LN.predictFcn(CTX)));
disp('Quadratic')
disp(mean(CTY==QN.predictFcn(CTX)));
disp('Cubic');
disp(mean(CTY==CN.predictFcn(CTX)));
disp('Fine');
disp(mean(CTY==FN.predictFcn(CTX)));
disp('Medium');
disp(mean(CTY==MN.predictFcn(CTX)));
disp('Coarse');
disp(mean(CTY==CoN.predictFcn(CTX)));